"""changed DJ model to take in arrays of objects for user_prefs and saved_playlists

Revision ID: ecc4929d6b4d
Revises: cdbed6b9d49f
Create Date: 2023-08-07 10:08:33.250900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc4929d6b4d'
down_revision = 'cdbed6b9d49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DJ',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logged_in', sa.Boolean(), nullable=True),
    sa.Column('user_prefs', sa.ARRAY(sa.PickleType()), nullable=True),
    sa.Column('saved_playlists', sa.ARRAY(sa.PickleType()), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('logged_in', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pref_genres', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pkey')
    )
    op.drop_table('DJ')
    # ### end Alembic commands ###
